/* ============================================================ levels */
const LEVELS = [
  { name: { fr: 'Premier aiguillage', en: 'First switch' }, speed: 2.6,
    hint: { fr: 'Touche un train pour le faire partir ou l\'arrêter. Touche un aiguillage pour changer sa direction.',
            en: 'Tap a train to start or stop it. Tap a switch to change its direction.' },
    tracks: [['L', 0, 0, 30, 0], ['T', 10, 0, 1, 1], ['L', 16, 3, 30, 3]],
    stations: [{ l: 'A', at: [0, 0] }, { l: 'C', at: [30, 0] }, { l: 'B', at: [30, 3] }],
    trains: [{ from: 'A', to: 'B', t0: 0, go: false }],
    switches: { '10,0': 0 },
    tutorial: [
      { anchor: 'switch:10,0', done: (g) => g.track.nodes.get('10,0').state === 1,
        fr: 'Cet aiguillage envoie les trains vers C. Touche-le pour l\'orienter vers B.',
        en: 'This switch sends trains to C. Tap it to point it toward B.' },
      { anchor: 'train:0', done: (g) => g.trains[0].go,
        fr: 'Ton train doit aller en B (sa lettre). Touche-le pour le faire partir.',
        en: 'Your train must reach B (its letter). Tap it to start it.' },
      { anchor: 'train:0', done: (g) => g.trains[0].state !== 'run',
        fr: 'Touche un train en marche pour l\'arrêter, et encore pour repartir. Utile quand deux trains se croisent.',
        en: 'Tap a moving train to stop it, and again to restart it. Handy when two trains cross.' },
    ] },
  { name: { fr: 'Deux aiguillages', en: 'Two switches' }, speed: 3,
    hint: { fr: 'Deux aiguillages à régler avant l\'arrivée. Arrête le train si tu as besoin de temps.',
            en: 'Two switches to set before arrival. Stop the train if you need time.' },
    tracks: [['L', 0, 3, 32, 3], ['T', 8, 3, 1, -1], ['L', 14, 0, 32, 0], ['T', 18, 3, 1, 1], ['L', 24, 6, 32, 6]],
    stations: [{ l: 'A', at: [0, 3] }, { l: 'B', at: [32, 0] }, { l: 'C', at: [32, 3] }, { l: 'D', at: [32, 6] }],
    trains: [{ from: 'A', to: 'D', t0: 0, go: true }],
    switches: { '8,3': 1, '18,3': 0 } },
  { name: { fr: 'La jonction', en: 'The junction' }, speed: 3.2,
    hint: { fr: 'Un train qui arrive par une branche traverse l\'aiguillage et le fait basculer de son côté. Le dernier aiguillage doit changer entre les deux trains.',
            en: 'A train arriving from a branch runs through the switch and flips it to its side. The last switch must change between the two trains.' },
    tracks: [['L', 0, 0, 36, 0], ['L', 0, 6, 10, 6], ['C', 10, 6, 16, 6, 16, 0, 22, 0], ['T', 26, 0, 1, 1], ['L', 32, 3, 36, 3]],
    stations: [{ l: 'A', at: [0, 0] }, { l: 'B', at: [0, 6] }, { l: 'C', at: [36, 0] }, { l: 'D', at: [36, 3] }],
    trains: [{ from: 'A', to: 'D', t0: 0, go: true }, { from: 'B', to: 'C', t0: 4, go: true }],
    switches: { '26,0': 0 } },
  { name: { fr: 'Le croisement', en: 'The crossover' }, speed: 3.4,
    hint: { fr: 'Les deux trains doivent changer de voie. Laisse passer le premier avant de lancer le second.',
            en: 'Both trains must change tracks. Let the first one through before starting the second.' },
    tracks: [['L', 0, 0, 36, 0], ['L', 0, 3, 36, 3], ['T', 10, 0, 1, 1], ['T', 20, 3, 1, -1]],
    stations: [{ l: 'A', at: [0, 0] }, { l: 'B', at: [0, 3] }, { l: 'C', at: [36, 0] }, { l: 'D', at: [36, 3] }],
    trains: [{ from: 'A', to: 'D', t0: 0, go: false }, { from: 'B', to: 'C', t0: 0, go: true }],
    switches: { '10,0': 0, '20,3': 0 } },
  { name: { fr: 'La voie d\'évitement', en: 'The passing loop' }, speed: 3.4,
    hint: { fr: 'Deux trains face à face sur une seule voie. Gare l\'un d\'eux dans la voie d\'évitement et arrête-le pendant que l\'autre passe.',
            en: 'Two trains head-on on a single track. Park one in the passing loop and stop it while the other goes by.' },
    tracks: [['L', 0, 0, 6, 0], ['T', 6, 0, -1, 1], ['L', 6, 0, 34, 0], ['L', 34, 0, 40, 0], ['T', 34, 0, 1, 1],
             ['T', 14, 0, 1, 1], ['L', 20, 3, 26, 3], ['T', 26, 3, 1, -1]],
    stations: [{ l: 'A', at: [0, 0] }, { l: 'C', at: [0, 3] }, { l: 'B', at: [40, 0] }, { l: 'D', at: [40, 3] }],
    trains: [{ from: 'A', to: 'D', t0: 0, go: true }, { from: 'B', to: 'C', t0: 0, go: true }],
    switches: { '6,0': 0, '14,0': 0, '32,0': 0, '34,0': 0 } },
  { name: { fr: 'Le triage', en: 'The yard' }, speed: 3.4,
    hint: { fr: 'Trois trains à 5 secondes d\'écart, trois destinations différentes. Prépare l\'aiguillage suivant dès qu\'un train est passé.',
            en: 'Three trains 5 seconds apart, three different destinations. Set the next switch as soon as a train has passed.' },
    tracks: [['L', 0, 3, 36, 3], ['T', 6, 3, 1, -1], ['L', 12, 0, 36, 0], ['T', 16, 3, 1, 1], ['L', 22, 6, 36, 6], ['T', 24, 0, 1, -1], ['L', 30, -3, 36, -3]],
    stations: [{ l: 'A', at: [0, 3] }, { l: 'B', at: [36, -3] }, { l: 'C', at: [36, 0] }, { l: 'D', at: [36, 3] }, { l: 'E', at: [36, 6] }],
    trains: [{ from: 'A', to: 'E', t0: 0, go: true }, { from: 'A', to: 'B', t0: 5, go: true }, { from: 'A', to: 'D', t0: 10, go: true }],
    switches: { '6,3': 0, '16,3': 0, '24,0': 0 } },
  { name: { fr: 'La voie médiane', en: 'The middle track' }, speed: 3.4,
    hint: { fr: 'Trois trains, deux entrées, une voie centrale partagée. Un seul train à la fois sur la voie du milieu.',
            en: 'Three trains, two entries, one shared middle track. Only one train at a time on it.' },
    tracks: [['L', 0, 0, 40, 0], ['L', 0, 6, 40, 6], ['L', 14, 3, 40, 3], ['T', 8, 0, 1, 1], ['T', 8, 6, 1, -1], ['T', 20, 3, 1, -1], ['T', 28, 3, 1, 1]],
    stations: [{ l: 'A', at: [0, 0] }, { l: 'B', at: [0, 6] }, { l: 'C', at: [40, 0] }, { l: 'D', at: [40, 3] }, { l: 'E', at: [40, 6] }],
    trains: [{ from: 'A', to: 'E', t0: 0, go: true }, { from: 'B', to: 'C', t0: 3, go: true }, { from: 'A', to: 'D', t0: 9, go: true }],
    switches: { '8,0': 0, '8,6': 0, '20,3': 0, '28,3': 0 } },
  { name: { fr: 'Deux évitements', en: 'Two passing loops' }, speed: 3.6,
    hint: { fr: 'Quatre trains, deux par sens, deux voies d\'évitement. Chaque croisement se fait dans un évitement, train à l\'arrêt.',
            en: 'Four trains, two per direction, two passing loops. Every meet happens in a loop, one train stopped.' },
    tracks: [['L', 0, 0, 6, 0], ['T', 6, 0, -1, 1], ['L', 6, 0, 46, 0], ['L', 46, 0, 52, 0], ['T', 46, 0, 1, 1],
             ['T', 10, 0, 1, 1], ['L', 16, 3, 20, 3], ['T', 20, 3, 1, -1],
             ['T', 27, 0, 1, 1], ['L', 33, 3, 37, 3], ['T', 37, 3, 1, -1]],
    stations: [{ l: 'A', at: [0, 0] }, { l: 'C', at: [0, 3] }, { l: 'B', at: [52, 0] }, { l: 'D', at: [52, 3] }],
    trains: [{ from: 'A', to: 'D', t0: 0, go: true }, { from: 'B', to: 'C', t0: 0, go: true }, { from: 'A', to: 'D', t0: 13, go: true }, { from: 'B', to: 'C', t0: 13, go: true }],
    switches: { '6,0': 0, '10,0': 0, '26,0': 0, '27,0': 0, '43,0': 0, '46,0': 0 } },
  { name: { fr: 'Contresens', en: 'Wrong way' }, speed: 3.6,
    hint: { fr: 'Un train arrive à contresens sur la voie du milieu, celle que les autres traversent. Quelqu\'un doit attendre.',
            en: 'One train comes the opposite way on the middle track, the one the others cross. Someone has to wait.' },
    tracks: [['L', 0, 0, 40, 0], ['L', 0, 3, 40, 3], ['L', 0, 6, 40, 6], ['T', 8, 0, 1, 1], ['T', 16, 6, 1, -1], ['T', 28, 3, 1, 1], ['T', 30, 3, 1, -1]],
    stations: [{ l: 'A', at: [0, 0] }, { l: 'B', at: [0, 6] }, { l: 'C', at: [40, 3] }, { l: 'D', at: [40, 0] }, { l: 'E', at: [40, 6] }, { l: 'F', at: [0, 3] }],
    trains: [{ from: 'A', to: 'E', t0: 0, go: true }, { from: 'B', to: 'D', t0: 3, go: true }, { from: 'C', to: 'F', t0: 7, go: true }, { from: 'A', to: 'D', t0: 14, go: true }],
    switches: { '8,0': 0, '14,3': 0, '16,6': 0, '22,3': 0, '28,3': 0, '30,3': 0 } },
  { name: { fr: 'Grande gare', en: 'Grand central' }, speed: 3.6,
    hint: { fr: 'Cinq trains, quatre voies, deux sens. Les trains qui traversent un aiguillage par une branche le font basculer: vérifie chaque aiguillage avant le train suivant.',
            en: 'Five trains, four tracks, both directions. Trains running through a switch from a branch flip it: check every switch before the next train.' },
    tracks: [['L', 0, 0, 40, 0], ['L', 0, 3, 40, 3], ['L', 0, 6, 40, 6], ['L', 0, 9, 40, 9],
             ['T', 6, 0, 1, 1], ['T', 16, 3, 1, 1], ['T', 8, 6, 1, -1], ['T', 18, 3, 1, -1],
             ['T', 36, 3, -1, 1], ['T', 28, 6, -1, 1], ['T', 38, 9, -1, -1], ['T', 26, 6, -1, -1]],
    stations: [{ l: 'A', at: [0, 0] }, { l: 'B', at: [0, 6] }, { l: 'C', at: [40, 3] }, { l: 'D', at: [40, 9] },
               { l: 'E', at: [40, 0] }, { l: 'F', at: [40, 6] }, { l: 'G', at: [0, 3] }, { l: 'H', at: [0, 9] }],
    trains: [{ from: 'A', to: 'F', t0: 0, go: true }, { from: 'C', to: 'H', t0: 0, go: true }, { from: 'B', to: 'E', t0: 4, go: true }, { from: 'D', to: 'G', t0: 7, go: true }, { from: 'A', to: 'E', t0: 13, go: true }],
    switches: {} },
];
